# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.1-linux-x86_64.tar.gz
    tar zxf julia-1.0.1-linux-x86_64.tar.gz
  displayName: 'Download and extract Julia'

- script: ./julia-1.0.1/bin/julia --project=@. -e 'using Pkg; Pkg.instantiate()'
  displayName: 'Install dependencies'

- script: |
    pwd
    ls $(Build.SourcesDirectory)
    ./julia-1.0.1/bin/julia --project=@. $(Build.SourcesDirectory)/build.jl
  displayName: 'Build Notebooks'

- checkout: self
  clean: false
  persistCredentials: true

- script: |
    git checkout -b 'build'
    git add build 
    git commit -m "add build directory"
    git push --set-upstream origin build
  displayName: 'git stuff'